# Generated by Django 4.2.11 on 2024-03-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut solicitante')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha ingreso')),
                ('nombre_solicitante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre solicitante')),
                ('preventiva', models.CharField(blank=True, max_length=255, null=True, verbose_name='Preventiva')),
                ('aprobar', models.BooleanField(blank=True, default=None, null=True, verbose_name='Aprobado')),
                ('fecha_atencion', models.DateField(blank=True, null=True, verbose_name='Fecha atencion')),
                ('hora_atencion', models.TimeField(blank=True, null=True, verbose_name='Hora atencion')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono solicitante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_cliente.usuario', to_field='usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
