# Generated by Django 4.2.11 on 2025-01-20 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_paquete', '0001_initial'),
        ('crear_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_encrip', models.TextField(blank=True, max_length=100, null=True, verbose_name='Encriptado')),
                ('valido', models.BooleanField(blank=True, default=None, null=True, verbose_name='Valido')),
                ('n_solicitud', models.IntegerField(blank=True, null=True, verbose_name='Numero solicitud')),
            ],
            options={
                'db_table': 'qr_solicitudes',
            },
        ),
        migrations.CreateModel(
            name='tipo_examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_examen', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipo_examen',
            },
        ),
        migrations.CreateModel(
            name='tipo_formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_formulario', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipo_formulario',
            },
        ),
        migrations.CreateModel(
            name='tipo_genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_genero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipo_genero',
            },
        ),
        migrations.CreateModel(
            name='solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_solicitud', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Cod solicitud')),
                ('n_solicitud', models.IntegerField(blank=True, null=True, verbose_name='Numero solicitud')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut solicitante')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha ingreso')),
                ('nombre_solicitante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre solicitante')),
                ('valido', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aprobado')),
                ('fecha_atencion', models.DateField(blank=True, null=True, verbose_name='Fecha atencion')),
                ('hora_atencion', models.TimeField(blank=True, null=True, verbose_name='Hora atencion')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono solicitante')),
                ('comentario', models.TextField(blank=True, max_length=160, null=True, verbose_name='Comentario')),
                ('ingresado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Ingreso')),
                ('agendado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Agendado')),
                ('nombre_medico', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre_medico')),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('tipo_formulario', models.TextField(blank=True, max_length=100, null=True, verbose_name='Formulario')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.paquete', to_field='cod_paquete', verbose_name='Paquete')),
                ('tipo_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='agendar_hora.tipo_examen', to_field='cod_examen', verbose_name='Tipo examen')),
                ('tipo_genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='agendar_hora.tipo_genero', to_field='cod_genero', verbose_name='Tipo genero')),
                ('tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_solicitud', to_field='cod_tipo_solicitud', verbose_name='Tipo solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_cliente.usuario', to_field='usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RegistroAnulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_anulacion', models.TextField(max_length=255, verbose_name='Motivo de Anulación')),
                ('fecha_anulacion', models.DateTimeField(default=datetime.datetime.today, verbose_name='Fecha de Anulación')),
                ('responsable', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nombre responsable')),
                ('cod_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendar_hora.solicitudes', verbose_name='cod_id')),
            ],
            options={
                'db_table': 'RegistroAnulado',
            },
        ),
    ]
