# Generated by Django 4.2.11 on 2024-03-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crear_paquete', '0001_initial'),
        ('agendar_hora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='preventiva',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='comentario',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.paquete', to_field='cod_paquete', verbose_name='Paquete'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='tipo_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_solicitud', to_field='cod_tipo_solicitud', verbose_name='Tipo solicitud'),
        ),
    ]
