# Generated by Django 4.2.11 on 2024-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar_hora', '0002_remove_solicitudes_preventiva_solicitudes_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_encrip', models.TextField(blank=True, max_length=100, null=True, verbose_name='Encriptado')),
                ('valido', models.BooleanField(blank=True, default=None, null=True, verbose_name='Valido')),
            ],
            options={
                'db_table': 'qr_solicitudes',
            },
        ),
    ]
