# Generated by Django 4.2.11 on 2024-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar_hora', '0003_qr_solicitudes'),
    ]

    operations = [
        migrations.CreateModel(
            name='derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_derivacion', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_examen', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_formulario', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
