# Generated by Django 4.2.11 on 2024-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendar_hora', '0004_derivacion_tipo_examen_tipo_formulario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='derivacion',
            table='derivacion',
        ),
        migrations.AlterModelTable(
            name='tipo_examen',
            table='tipo_examen',
        ),
        migrations.AlterModelTable(
            name='tipo_formulario',
            table='tipo_formulario',
        ),
    ]
