# Generated by Django 4.2.11 on 2025-01-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendar_hora', '0001_initial'),
        ('crear_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_encrip', models.TextField(blank=True, max_length=100, null=True, verbose_name='Encriptado')),
                ('valido', models.BooleanField(blank=True, default=None, null=True, verbose_name='Valido')),
                ('n_examen', models.IntegerField(blank=True, null=True, verbose_name='Numero examen')),
                ('cod_examen', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Cod examen')),
            ],
            options={
                'db_table': 'qr_examen',
            },
        ),
        migrations.CreateModel(
            name='examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_examen', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Cod examen')),
                ('n_examen', models.IntegerField(blank=True, null=True, verbose_name='Numero examen')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut paciente')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha ingreso')),
                ('nombre_paciente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre paciente')),
                ('valido', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aprobado')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono paciente')),
                ('comentario', models.TextField(blank=True, max_length=160, null=True, verbose_name='Comentario')),
                ('recepcionado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Recepcionado')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha recepcion')),
                ('tipo_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='agendar_hora.tipo_examen', to_field='cod_examen', verbose_name='Tipo examen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_cliente.usuario', to_field='usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'examenes',
            },
        ),
    ]
