# Generated by Django 4.2.11 on 2025-01-20 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paquete', models.CharField(max_length=100, unique=True, verbose_name='Codigo paquete')),
                ('nombre_paquete', models.TextField(max_length=100, verbose_name='nombre_paquete')),
            ],
            options={
                'db_table': 'paquete',
            },
        ),
        migrations.CreateModel(
            name='tipo_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_solicitud', models.CharField(max_length=5, unique=True, verbose_name='Codigo tipo solicitud')),
                ('tipo_solicitud', models.TextField(max_length=100, verbose_name='tipo de solicitud')),
                ('empresa', models.BooleanField(blank=True, default=False, null=True, verbose_name='Empresa')),
                ('mutual', models.BooleanField(blank=True, default=False, null=True, verbose_name='Mutual')),
            ],
            options={
                'db_table': 'tipo_solicitud',
            },
        ),
        migrations.CreateModel(
            name='tipo_prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_prestacion', models.CharField(max_length=5, unique=True, verbose_name='Codigo tipo prestacion')),
                ('tipo_prestacion', models.TextField(max_length=100, verbose_name='tipo de prestacion')),
                ('cod_tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_solicitud', to_field='cod_tipo_solicitud')),
            ],
            options={
                'db_table': 'tipo_prestacion',
            },
        ),
        migrations.CreateModel(
            name='prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prestacion', models.CharField(max_length=20, unique=True, verbose_name='Codigo prestacion')),
                ('cod_fonasa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo fonasa')),
                ('prestacion', models.TextField(max_length=100, verbose_name='prestacion')),
                ('codigo_interno', models.CharField(blank=True, max_length=12, null=True, verbose_name='cod_interno')),
                ('ingresado', models.BooleanField(blank=True, default=True, null=True, verbose_name='ingresado')),
                ('cod_tipo_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_prestacion', to_field='cod_tipo_prestacion')),
            ],
            options={
                'db_table': 'prestacion',
            },
        ),
        migrations.CreateModel(
            name='paquete_prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.paquete', to_field='cod_paquete')),
                ('cod_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.prestacion', to_field='cod_prestacion')),
                ('cod_tipo_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_prestacion', to_field='cod_tipo_prestacion')),
            ],
            options={
                'db_table': 'paquete_prestacion',
            },
        ),
        migrations.CreateModel(
            name='Anulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_anulacion', models.TextField(max_length=255, verbose_name='Motivo de Anulación')),
                ('fecha_anulacion', models.DateTimeField(default=datetime.datetime.today, verbose_name='Fecha de Anulación')),
                ('responsable', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nombre responsable')),
                ('ingresar_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crear_paquete.prestacion', to_field='cod_prestacion', verbose_name='cod_prestacion')),
            ],
            options={
                'db_table': 'Anulado',
            },
        ),
    ]
