# Generated by Django 4.2.11 on 2024-03-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paquete', models.CharField(unique=True, verbose_name='Codigo paquete')),
                ('nombre_paquete', models.TextField(max_length=100, verbose_name='nombre_paquete')),
            ],
            options={
                'db_table': 'paquete',
            },
        ),
        migrations.CreateModel(
            name='tipo_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_solicitud', models.CharField(max_length=5, unique=True, verbose_name='Codigo tipo solicitud')),
                ('tipo_solicitud', models.TextField(max_length=100, verbose_name='tipo de solicitud')),
            ],
            options={
                'db_table': 'tipo_solicitud',
            },
        ),
        migrations.CreateModel(
            name='tipo_prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_prestacion', models.CharField(max_length=5, unique=True, verbose_name='Codigo tipo prestacion')),
                ('tipo_prestacion', models.TextField(max_length=100, verbose_name='tipo de prestacion')),
                ('cod_tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_solicitud', to_field='cod_tipo_solicitud')),
            ],
            options={
                'db_table': 'tipo_prestacion',
            },
        ),
        migrations.CreateModel(
            name='prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prestacion', models.CharField(max_length=5, unique=True, verbose_name='Codigo prestacion')),
                ('prestacion', models.TextField(max_length=100, verbose_name='prestacion')),
                ('cod_tipo_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_prestacion', to_field='cod_tipo_prestacion')),
            ],
            options={
                'db_table': 'prestacion',
            },
        ),
        migrations.CreateModel(
            name='paquete_prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.paquete', to_field='cod_paquete')),
                ('cod_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.prestacion', to_field='cod_prestacion')),
                ('cod_tipo_prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_paquete.tipo_prestacion', to_field='cod_tipo_prestacion')),
            ],
            options={
                'db_table': 'paquete_prestacion',
            },
        ),
    ]
