# Generated by Django 4.2.11 on 2024-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo empresa')),
                ('nombre_empresa', models.TextField(blank=True, max_length=100, null=True, verbose_name='Nombre empresa')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
