# Generated by Django 4.2.11 on 2025-01-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mutualidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_mutual', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo mutual')),
                ('nombre_mutual', models.TextField(blank=True, max_length=100, null=True, verbose_name='Nombre mutual')),
                ('rut', models.TextField(blank=True, max_length=100, null=True, verbose_name='Rut')),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.TextField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
            ],
            options={
                'db_table': 'mutualidades',
            },
        ),
        migrations.CreateModel(
            name='tipo_organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo tipo')),
                ('nombre_tipo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Nombre tipo')),
            ],
            options={
                'db_table': 'tipo_organizacion',
            },
        ),
        migrations.CreateModel(
            name='utms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_utms', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo utms')),
                ('nombre_utms', models.TextField(blank=True, max_length=100, null=True, verbose_name='Nombre utms')),
                ('rut', models.TextField(blank=True, max_length=100, null=True, verbose_name='Rut')),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.TextField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
            ],
            options={
                'db_table': 'utms',
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo empresa')),
                ('nombre_empresa', models.TextField(blank=True, max_length=100, null=True, verbose_name='Nombre empresa')),
                ('rut', models.TextField(blank=True, max_length=100, null=True, verbose_name='Rut')),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.TextField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('mutualidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_empresa.mutualidades', to_field='cod_mutual', verbose_name='mutual')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
