# Generated by Django 4.2.11 on 2025-01-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_organizacion',
            name='nombre_tipo',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Nombre tipo'),
        ),
    ]
