# Generated by Django 4.2.11 on 2024-03-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_empresa.empresa', to_field='cod_empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
