# Generated by Django 4.2.11 on 2025-01-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.TextField(blank=True, max_length=100, null=True, verbose_name='Rut')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_empresa.empresa', to_field='cod_empresa', verbose_name='Empresa')),
                ('mutualidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_empresa.mutualidades', to_field='cod_mutual', verbose_name='Mutualidad')),
                ('utm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crear_empresa.utms', to_field='cod_utms', verbose_name='Utms')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
